<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Hex on Blog - uTIcARdI</title><link>https://blog.gainskills.top/tags/hex/</link><description>Recent content in Hex on Blog - uTIcARdI</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Mon, 02 Dec 2019 00:00:00 +0000</lastBuildDate><atom:link href="https://blog.gainskills.top/tags/hex/index.xml" rel="self" type="application/rss+xml"/><item><title>An incompatible issue of xls file</title><link>https://blog.gainskills.top/2019/12/02/pyxlwtdebug/</link><pubDate>Mon, 02 Dec 2019 00:00:00 +0000</pubDate><guid>https://blog.gainskills.top/2019/12/02/pyxlwtdebug/</guid><description>Background An integration project: exporting a csv file from system A, convert the csv file to xls file and import the converted file into system B (A 3rd party system).
Environment:
Python3.7.5 xls library: xlwt1.3 Developing on Mac 10.15.1 with VS Code, and finally the project will be published to a Docker environment(ritht now, it's Python:3.7.5-alpine3.10). Issue The converted xls file, system B doesn't support it. However, the file can be opened in Microsoft Excel, and then system B supports it after the open operation (did nothing, just open it then close)ðŸ˜«.</description></item></channel></rss>